In [1]:
import pandas as pd

Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.

In [2]:
#Answer:- Creating a variable which holds the series elements. Converting and printing the series
l = [4, 8, 15, 16, 23, 42 ]
l1 = pd.Series(l)
print(l1)

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64


Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the
variable print it.

In [11]:
#Answer:- Creating list type veriable containing different data types. Converting and printing it in series type.
l2 = [1,4,'Text',23.4,False,'Text2',45,32,12,12.6]
s1 = pd.Series(l2)
print(s1)

0        1
1        4
2     Text
3     23.4
4    False
5    Text2
6       45
7       32
8       12
9     12.6
dtype: object


Q3. Create a Pandas DataFrame that contains the following data:

In [15]:
data = {'Name':['Alice','Bob','Claire'],
        'Age': [25,30,27],
        'Gender' : ['Female','Male','Female']}
df = pd.DataFrame(data)
df

Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.

Answer:-
    
    DataFrame:-
          In Pandas, DataFrame is a 2 dimensional tabular structure of data which comprises the combination of rows and columns. Each column can have           elements of same data type and each row is an observation.
          
    Series:-
          In Pandas, Series is a singale dimensioanl structure of the data which can hold elements of any data type within. It could be represt as               single column of a dataframe
          
The main distinction between the two is this. For a single-column DataFrame, an index can be optional, but a Series has to have an index defined.

Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can
you give an example of when you might use one of these functions?

Answer:- 
    
    Some common functions to manipulate data in Pandas Dataframe are: map(), Apply(), Applymap()
 Map() function is typically used with series data type where we desire to manipulate the data. Lets say I want to change the data in the date column        to a specific date format. I can use the Map() function which will map my desired date formate to all the elements of the date column.
 
 Apply()
       Apply function can be used with both series and dataframe. It also offeres similar functionality as to map function. We can apply different            methods of our requiremet on dataframe or series as we required

Applymap()
       Applymap is specifically used with dataframes and offers sprt of similar functionality. Although, difference of applymap is that it maps a function on the dataset element-wise

Q6. Which of the following is mutable in nature Series, DataFrame, Panel?

Answer:-
Series:- Series is 1 dimensional data structure which is immutable in nature

DataFrame:- DataFrame is 2 dimensional data structure which is mutable in nature

Panel:- panle is 3 dimensional data structure which is also mutable in nature

Q7. Create a DataFrame using multiple Series. Explain with an example.

In [32]:
#Following is a dummy data which represent the daily expenses of the single week
Data = {'Days':['Monday','Tuesday',
               'Wednesday', 'Thursday', 'Friday',
               'Saturday','Sunday'],
       'Daily Expense': [200,167,300,321,243,421,356]}
df1 = pd.DataFrame(Data)
df1

Days  Daily Expense
0     Monday            200
1    Tuesday            167
2  Wednesday            300
3   Thursday            321
4     Friday            243
5   Saturday            421
6     Sunday            356

In [34]:
df1.shape #Checking shape of data set

(7, 2)

In [38]:
df1.info() # fetching info of the data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Days           7 non-null      object
 1   Daily Expense  7 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 240.0+ bytes


In [39]:
df1.describe()

Daily Expense
count       7.000000
mean      286.857143
std        89.393192
min       167.000000
25%       221.500000
50%       300.000000
75%       338.500000
max       421.000000

Conclusion:- 
Data shows that average daily expense of the individual is 286 which means he spends 286 on daily basis
We can also see that his minimum spend is 167 of the week and maximum is 421
We can also observe that there is a high standard deviation which means values are more widly spread out from the mean/median in the dataset
